import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { BannerInfo } from "../bannerTypes";
import imageLoader from "../imageLoader";
import styles from "../styles/Home.module.css";

const Home: NextPage<{ bannersInfo: BannerInfo[] }> = ({
  bannersInfo,
}: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h1>Banner Info</h1>
          {bannersInfo.map((banner: BannerInfo) => (
            <div key="{banner.id}">
              <div>{banner.title1}</div>
              <div>{banner.title2}</div>
              <div>{banner.title3}</div>
              <div>{banner.title4}</div>
              {banner.asterisk}
              <div>
                <Image
                  loader={imageLoader}
                  unoptimized
                  src={
                    "https://cms.beautiskinclinic.com" +
                    banner.image.formats.large.url
                  }
                  alt={banner.image.alternativeText}
                  width={300}
                  height={100}
                />
              </div>
            </div>
          ))}
        </div>

        <a
          href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          className={styles.card}
        >
          <h2>Link</h2>
        </a>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
        </a>
      </footer>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const response = await fetch(
    "http://cms.beautiskinclinic.com/homepage-sliders"
  );

  // Parse the JSON
  const bannersInfo = await response.json();

  // Finally we return the result
  // inside props as allPokemons
  return {
    props: { bannersInfo },
  };
};

export default Home;
